import 'dart:ui';
import 'package:flutter/material.dart';

class Products {
  final String image, title, description,dressDescription, footwearDescription, price, footwearPrice, dressPrice, dressName, dressImage, footwearName, footwearImage;
  final int size, id;
  final Color color;

  Products({
    required this.id,
    required this.dressImage,
    required this.dressName,
    required this.footwearImage,
    required this.footwearName,
    required this.image,
    required this.title,
    required this.description,
    required this.price,
    required this.size,
    required this.color,
    required this.footwearPrice,
    required this.dressPrice,
    required this.dressDescription,
    required this.footwearDescription

  });
}

List<Products> products = [

  Products(
      id: 1,
      image: "assets/icons/handbag1.png",
      dressImage: "assets/icons/dress.png",
      footwearImage: "assets/icons/footwear2.png",
      title: "Office code",
      dressName: "Casual wear",
      footwearName: "Ankle strap",
      description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
      price: "250.0",
      footwearPrice: "500.0",
      dressPrice: "750.0",
      size: 12,
      color: Colors.pink.shade700,
      dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
      footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 2,
    image: "assets/icons/handbag2.png",
    dressImage: "assets/icons/dress1.png",
    footwearImage: "assets/icons/footwear3.png",
    dressName: "Knife pleated",
    footwearName: "T-strap",
    title: "Alphabeto nano",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "350.0",
    footwearPrice: "400.0",
    dressPrice: "800.0",
    size: 15,
    color: Colors.blueGrey,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 3,
    image: "assets/icons/handbag3.png",
    dressImage: "assets/icons/dress2.png",
    footwearImage: "assets/icons/footwear4.png",
    title: "Cherry shoulder",
    dressName: "paneled skirt",
    footwearName: "Open toe",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "320.0",
    footwearPrice: "410.0",
    dressPrice: "850.0",
    size: 20,
    color: Colors.red.shade900,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 4,
    image: "assets/icons/handbag4.png",
    dressImage: "assets/icons/dress3.png",
    footwearImage: "assets/icons/footwear5.png",
    title: "Sunshine shoulder",
    dressName: "Accordian",
    footwearName: "Scarpin",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "620.0",
    footwearPrice: "760.0",
    dressPrice: "1500.0",
    size: 13,
    color: Colors.grey,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 5,
    image: "assets/icons/handbag5.png",
    dressImage: "assets/icons/dress4.png",
    footwearImage: "assets/icons/footwear6.png",
    title: "Play work bag",
    dressName: "Cardign",
    footwearName: "Peep toe",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "300.0",
    footwearPrice: "640.0",
    dressPrice: "500.0",
    size: 16,
    color: Colors.blueGrey,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 6,
    image: "assets/icons/handbag6.png",
    dressImage: "assets/icons/dress5.png",
    footwearImage: "assets/icons/footwear2.png",
    title: "Beige sling",
    dressName: "Party wear",
    footwearName: "Wedge booties",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "820.0",
    footwearPrice: "750.0",
    dressPrice: "900.0",
    size: 18,
    color: Colors.red.shade700,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 7,
    image: "assets/icons/handbag7.png",
    dressImage: "assets/icons/dress6.png",
    footwearImage: "assets/icons/footwear7.png",
    title: "Sling",
    dressName: "Wrap skirt",
    footwearName: "Oxford",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "450.0",
    footwearPrice: "455.0",
    dressPrice: "1099.0",
    size: 22,
    color: Colors.brown.shade400,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 8,
    image: "assets/icons/handbag8.png",
    dressImage: "assets/icons/dress7.png",
    footwearImage: "assets/icons/footwear1.png",
    title: "Shoulder bag",
    dressName: "Ruffeld wear",
    footwearName: "Loafer",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "360.0",
    footwearPrice: "1200.0",
    dressPrice: "450.0",
    size: 14,
    color: Colors.grey.shade700,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
  Products(
    id: 9,
    image: "assets/icons/handbag8.png",
    dressImage: "assets/icons/dress5.png",
    footwearImage: "assets/icons/footwear1.png",
    title: "Beige handheld",
    dressName: "Casual wear",
    footwearName: "Cone heels",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "380.0",
    footwearPrice: "500.0",
    dressPrice: "1700.0",
    size: 14,
    color: Colors.grey.shade700,
    dressDescription:"Boutique is a small shop selling fashionable clothes or accessories. It is also know as a business serving a sophisticated or specialized clientele. The term “boutique” and also “designer” refer (with some differences) to both goods and services which are containing some element that is claimed to justify an extremely high price, is known as boutique pricing. Boutique has various types of fabrics which one can select, match to his/her look and design in a garment. It also has semi stitched or full stitched ready to wear a fashionable garments. An individual could select them and alter it, if needed to provide good fit.",
    footwearDescription:"In cultures where bare feet are customary or only simple sandals are worn, little interest exists in the female foot as a sensual appendage. However, hidden away in tight, decorative shoes and boots, the female foot has been revered as a powerful sexual stimulus in many cultures. Smaller and narrower than a man's foot, the attributes of a woman's comparatively delicate foot has been appreciated and accentuated throughout much of history. This is most apparent in the extreme practice of Chinese foot binding.",
  ),
];
