import 'dart:ui';
import 'package:flutter/material.dart';

class Products {
  final String image, title, description, price, dressName, dressImage, footwearName, footwearImage;
  final int size, id;
  final Color color;

  Products({
    required this.id,
    required this.dressImage,
    required this.dressName,
    required this.footwearImage,
    required this.footwearName,
    required this.image,
    required this.title,
    required this.description,
    required this.price,
    required this.size,
    required this.color,
  });
}

List<Products> products = [

  Products(
      id: 1,
      image: "assets/icons/handbag1.png",
      dressImage: "assets/icons/footwear1.png",
      footwearImage: "assets/icons/footwear2.png",
      title: "Office code",
      dressName: "Office code",
      footwearName: "Office code",
      description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
      price: "250.0",
      size: 12,
      color: Colors.pink.shade700,
  ),
  Products(
    id: 2,
    image: "assets/icons/handbag2.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear3.png",
    dressName: "Office code",
    footwearName: "Office code",
    title: "pppppppp",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 15,
    color: Colors.blueGrey,
  ),
  Products(
    id: 3,
    image: "assets/icons/handbag3.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear4.png",
    title: "Office code",
    dressName: "Office code",
    footwearName: "Office code",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 20,
    color: Colors.red.shade900,
  ),
  Products(
    id: 4,
    image: "assets/icons/handbag4.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear5.png",
    title: "Office code",
    dressName: "Office code",
    footwearName: "Office code",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 13,
    color: Colors.grey,
  ),
  Products(
    id: 5,
    image: "assets/icons/handbag5.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear6.png",
    title: "Office code",
    dressName: "Office code",
    footwearName: "Office code",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 16,
    color: Colors.blueGrey,
  ),
  Products(
    id: 6,
    image: "assets/icons/handbag6.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear2.png",
    title: "Office code",
    dressName: "Office code",
    footwearName: "Office code",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 18,
    color: Colors.red.shade700,
  ),
  Products(
    id: 7,
    image: "assets/icons/handbag7.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear7.png",
    title: "Office code",
    dressName: "Office code",
    footwearName: "Office code",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 22,
    color: Colors.brown.shade400,
  ),
  Products(
    id: 8,
    image: "assets/icons/handbag8.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear1.png",
    title: "Office code",
    dressName: "Office code",
    footwearName: "Office code",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 14,
    color: Colors.grey.shade700,
  ),
  Products(
    id: 9,
    image: "assets/icons/handbag8.png",
    dressImage: "assets/icons/footwear1.png",
    footwearImage: "assets/icons/footwear1.png",
    title: "Office code",
    dressName: "Office code",
    footwearName: "Office code",
    description: "a bag or box of leather, fabric, plastic, or the like, held in the hand or carried by means of a handle or strap, commonly used for holding money, personal grooming items, small purchases, etc.",
    price: "250.0",
    size: 14,
    color: Colors.grey.shade700,
  ),
];
